- name: Install letsencrypt
  package:
    name: "{{ nginx_package }}"
    state: present

- name: Install letsencrypt packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nginx_letsencrypt_packages }}"

    # - name: Execute certbot
    #   shell:
    #     cmd: "certbot -n --nginx -d {{ nginx_domain_name }} --email {{ letsencrypt_notification_email }} --agree-tos"
    #     #   notifiy: Restart Nginx
